### ISSUE TITLE
Does not work with UTF-8 files.

### ISSUE THREAD

**Issue by wengych** [vowstar/gitbook-plugin-uml#15]
![image](https://user-images.githubusercontent.com/57008/71350750-f5671e80-25ac-11ea-869e-f7deaa87576e.png)
The puml file contain Chinese words then this plugin can not work fine.

**Comment by wengych** [comment]
Related document on plantuml:
https://plantuml.com/zh/text-encoding

**Comment by wengych** [comment]
![image](https://user-images.githubusercontent.com/57008/71351010-9f46ab00-25ad-11ea-8b21-c0e3f2438c6d.png)
Last year it works for me by a simple hack on node-plantuml, but it does not work now.

**Comment by vowstar** [comment]
Hello @wengych , thank you for your report.

I've test it with my environment, but the result is good.

I think there may be some environmental problems, and your information is not enough to solve this problem.

Can you check the environment or node version? And related error output? I cannot reproduce your problem here, so I can only solve it by guessing.

Please run ```locale``` command in your shell, 

```bash

locale

```

and let me check your output, a ```utf8``` locale must  be used, such as ```zh_cn.utf-8``` or ```en_US.utf8```, etc.

My locale is:

```bash
$ locale

LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

My test README.md is

```markdown
# Introduction

```puml
@startuml

(简体中文)<->(繁體中文)

@enduml
```

```

My test book.json is

```json
{
    "plugins": [
        "-highlight",
        "uml"
    ],
    "pdf": {
        "margin": {
            "top": 36,
            "bottom": 36
        },
        "toc": true
    },
    "structure": {
        "readme": "README.md",
        "summary": "SUMMARY.md"
    },
    "title": "test",
    "language": "zh-hans"
}
```

My command is 

```bash
gitbook install
gitbook build
gitbook serve
```

Version info

```
node -v
v12.9.1

npm -v
6.13.4

gitbook -V
CLI version: 2.3.2
GitBook version: 3.2.3
```

My result is

![Screenshot from 2020-01-03 09-18-53](https://user-images.githubusercontent.com/394260/71702377-1b40be80-2e0a-11ea-8114-f6d794765292.png)

I think it works.
